### ISSUE TITLE
Редактирование л/р3 по Kubernetes

### ISSUE THREAD

**Issue by Hrenaki** [itmo-ict-faculty/introduction-to-distributed-technologies#11]
1. В ход работы необходимо добавить ещё один шаг перед заключительным по созданию minikube tunnel к созданному в [этой л/р](https://itmo-ict-faculty.github.io/introduction-to-distributed-technologies/education/labs2022_2023/lab3/lab3/) ingress, если студент выполняет её на Windows или macOS.
2.  Также необходимо в нынешнем предпоследнем пункте (где hosts) необходимо указать, что если студент выполняет работу на Windows или macOS, то в файл 'hosts' нужно указывать loopback ip (127.0.0.1) вместо minikube ip.

Предлагаю внести эти уточнения в связи с отсутствием прямого доступа к ingress на Windows и macOS (см. 
[minikube issue](https://github.com/kubernetes/minikube/issues/13951)), и решением этой проблемы является создание тоннеля (см. пункт 2 или в [источнике](https://stackoverflow.com/questions/58561682/minikube-with-ingress-example-not-working)).

**Comment by adeptvin1** [comment]
Fixed in https://github.com/itmo-ict-faculty/introduction-to-distributed-technologies/pull/12
