### ISSUE TITLE
Дополнительная информация по курсу

### ISSUE THREAD

**Issue by adeptvin1** [itmo-ict-faculty/introduction-to-distributed-technologies#6]
@adeptvin1 , у меня есть вопрос по курсу. Нужно ли прикладывать ссылку на статью в мой репозиторий и если да, то куда.

**Comment by 0xYanis** [comment]
[QUESTION]
@adeptvin1 , у меня есть вопрос по курсу. Нужно ли прикладывать ссылку на статью в мой репозиторий и если да, то куда.

**Comment by adeptvin1** [comment]
@0xYanis , здравствуйте. Да, нужно. Я расписал требования вот [тут](https://github.com/itmo-ict-faculty/introduction-to-distributed-technologies/commit/3dfeeed5b88160b5fbed4c20dd99ffc6baf3ccb4). В течении нескольких дней соберем все правки и я вмержу в основную ветку все изменения.

**Comment by adeptvin1** [comment]
@0xYanis, у вас есть дополнения/замечания по описанию курса? Я добавил страницу с статьями прошлых лет и добавил раздел с требованиями к статье на medium/habr.

**Comment by 0xYanis** [comment]
@adeptvin1, вы про этот [раздел](https://github.com/itmo-ict-faculty/introduction-to-distributed-technologies/commit/3dfeeed5b88160b5fbed4c20dd99ffc6baf3ccb4)? Все понятно, вопросов по статье нет. Интересует способ сдачи лабораторных по кубам, в описании к курсу написано что сдача возможно на лабораторных по расписанию, но в расписании л/р нет, есть только лекции и практики. Можно защититься на этих парах?

**Comment by adeptvin1** [comment]
@0xYanis, я буду принимать лабы на следующей практике (завтра). По факту лабораторное/практическое занятие не сильно отличаются по смыслу.

**Comment by adeptvin1** [comment]
@0xYanis, я вмержил изменения, теперь версия v1.0.1, закрываю issue как решенную.
